### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/node-module-glpi#15]
Hi, @Naylin15  

Could you add a compatibility matrix to the README file?

Similar to this format:

|GLPI|9.1.1|9.1.2|9.1.3|9.2.0|
|:----|----|----|----|---|
|**GLPI API Client**|1.x.x|1.x.x|1.x.x| 2.0.0-dev |

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done in #17
